Scaffold front page
interglobalvision/linear-city-com pull request #7
Opened 2017-07-21 22:14 UTC by mixcas

Scaffolds each section in `front-page.php`:
- Splash
- Properties Grid
- What we do
- Press
- Filming

Also styles `.splash-with-image` a little

2017-07-22 12:35 UTC, varffs requested changes

2017-07-22 12:35 UTC, varffs commented on lib/meta-boxes.php
> +  $cmb_what_we_do->add_field( array(
This errors as undefined:

```
Notice: Undefined variable: cmb_what_we_do in /Users/patrickbest/Sites/wp/linear/wp-content/themes/linear-city-com/lib/meta-boxes.php on line 137

Fatal error: Call to a member function add_field() on null in /Users/patrickbest/Sites/wp/linear/wp-content/themes/linear-city-com/lib/meta-boxes.php on line 137
```

2017-07-22 12:35 UTC, varffs commented on lib/meta-boxes.php
> +  $cmb_what_we_do->add_field( array(
Which will always happen if the pages are not created. Same for the rest. So the pages either need to be created in the theme with a hook and/or this conditionals fixed

2017-07-22 12:37 UTC, varffs commented on partials/home-press-quotes.php
> +$home = get_page_by_path('home');
I don't really like this pattern for data here. The home page's content is never needed or displayed the home page is just a place where metavalues are set? Seems cleaner to me to just have that meta set in the site options. This is obviously a point of discussion

2017-07-24 14:50 UTC, mixcas commented on lib/meta-boxes.php
> +  $cmb_what_we_do->add_field( array(
Ah shit, these are supposed to be inside the condition. will fix

2017-07-26 12:38 UTC, varffs requested changes
A few things but the erroring page thing does need to be fixed. @mikeyrayvon feel free to close after @mixcas fixes it up

2017-07-26 12:38 UTC, varffs commented on partials/home-splash.php
> +$splash_text = get_post_meta($home->ID,'_igv_splash_text', true);
this depends on a `home` page existing and thus errors when the page doesn't exist.

2017-07-26 12:38 UTC, varffs commented on partials/home-splash.php
> +$splash_text = get_post_meta($home->ID,'_igv_splash_text', true);
I think for themes which depend on certain pages existing we should do init checks and create the pages programatically: https://developer.wordpress.org/reference/functions/wp_insert_post/#parameters

2017-07-26 12:38 UTC, varffs commented on partials/properties-grid.php
> +$properties = new WP_QUERY( array(
weird capitialization of `WP_Query` but it works...

2017-07-26 12:38 UTC, varffs commented on partials/properties-grid.php
> +        <article class="u-alert grid-item item-s-12"><?php _e('Sorry, no posts matched your criteria :{'); ?></article>
This will break the layout. It isn't really needed in this case so better to just remove the `else`

2017-07-26 12:38 UTC, varffs commented on partials/home-splash.php
> +$splash_text = get_post_meta($home->ID,'_igv_splash_text', true);
but then again you have the conditional for the other partials so that works too it is just missing

2017-07-27 18:44 UTC, mixcas commented on partials/home-splash.php
> +$splash_text = get_post_meta($home->ID,'_igv_splash_text', true);
U r fully right

2017-07-28 11:18 UTC, varffs approved these changes

2017-07-28 11:18 UTC, merged